name: example
description: A new Flutter project.

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:

  flutter:
    sdk: flutter

  pull_to_refresh:
    path: ../
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
 
flutter:
 
  uses-material-design: true
 